### ISSUE TITLE
Separate CleanSlate from nginx deployment

### ISSUE THREAD

**Issue by guidopetri** [successible/cleanslate#172]
It seems pretty easy to self-host CleanSlate with HTTPS because nginx is baked into the `Dockerfile.client` image, but some self-hosters don't use nginx as a reverse proxy or want to use a different reverse proxy, e.g. Caddy. Is it possible to divorce the Dockerfile from having nginx installed, and instead serve the application on a Docker-published port?

**Comment by paulzakin** [comment]
Yup, I think that is a good idea - closed in #174

**Comment by paulzakin** [comment]
Let me know if that solves your problem - the `README.md` should explain the changes!

**Comment by guidopetri** [comment]
Hmm, this doesn't quite accomplish what I had in mind. Personally I'd prefer to get rid of the double-stacked proxy - i.e. have cleanslate be its own application without any proxy as part of it. I think this would simplify debugging as well since there would only be one nginx conf file to handle and not two, with potential interactions.

**Comment by paulzakin** [comment]
So

**Comment by paulzakin** [comment]
So - the Clean Slate client is not a application - it's literally just a static /build directory from Next.js. So, if it I want to keep it in the Docker container, I suppose I can just have the Docker compose mount a volume - putting that directory on the outside of the container, to be picked up by a reverse proxy?

**Comment by paulzakin** [comment]
But that honestly seems MORE complicated than just treating Clean Slate as an application by have it run nginx under the hood - so I'm not inclined to change it unless you have a better idea!

**Comment by paulzakin** [comment]
Alternatively, I could just have the client Docker container have a Node.js server that serves the static directory and leave the proxy passing to the reverse proxy - however, I guess I’m just not that concerned about the debugging from two proxies vs. one - so I am inclined to leave it as such.

**Comment by guidopetri** [comment]
I see. Honestly, yeah, I'd prefer it if it were just a mounted volume that nginx served, or a nodejs server for the static directory. I'm going to experiment with my own deployment and see what I land on now that I understand a bit better how Cleanslate is set up.

Thanks for the change in #174 ! And thanks for being so nice about it :)

**Comment by paulzakin** [comment]
Of course! And obviously - PRs welcome if you have any better ideas

**Comment by guidopetri** [comment]
I set it up as follows (incomplete snippet):

```yaml
  cleanslate_backend:
    build:
      context: https://github.com/successible/cleanslate.git#main
      dockerfile: Dockerfile.server
    container_name: cleanslate_backend
    restart: always
    ports:
      - "127.0.0.1:9789:8080"
    env_file: ${HOME}/.env_files/.cleanslate_env

  cleanslate_frontend_builder:
    build:
      context: https://github.com/successible/cleanslate.git#main
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_VERSION=gpetri-b1d904c
        - NEXT_PUBLIC_HASURA_DOMAIN=cleanslate.${SITE_HOSTNAME}
    entrypoint: ''
    command: '/bin/bash'
    container_name: cleanslate_frontend
    restart: no
    depends_on:
      - cleanslate_backend
    volumes:
      - certbot_ssl:/etc/ssl:ro
      - cleanslate_files:/build
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ${HOME}/.env_files/.nginx_env
    volumes:
      - certbot_ssl:/etc/nginx/ssl/:ro  # ssl cert location
      - cleanslate_files:/cleanslate
```

This works alright. Once the `cleanslate_frontend_builder` service is run, it creates the `/build` contents within that get synced to the `cleanslate_files` volume, shared with the nginx service. I suspect I have to set this to `:ro` still.

To deploy, it appears that I have to:
- `docker stop nginx`
- `docker rm cleanslate_frontend_builder`
- `docker compose build cleanslate_frontend_builder`
- `docker compose up cleanslate_frontend_builder`
- `docker start nginx`

I think that setting the volume on the nginx side to `:ro` will allow me to skip the first and last step, but I'll give that a shot some other time. The `cleanslate_frontend_builder` container now runs just once and doesn't restart, and I only have `cleanslate_backend` running consistently, and nginx serves the files perfectly fine with the following conf:

```
server {
	listen 80;
	listen [::]:80;

	server_name cleanslate.__HOSTNAME__;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
    http2 on;

	server_name cleanslate.__HOSTNAME__;
	root /cleanslate;

	ssl_certificate /etc/nginx/ssl/live/__HOSTNAME__/fullchain.pem;
	ssl_certificate_key /etc/nginx/ssl/live/__HOSTNAME__/privkey.pem;
	ssl_session_timeout 1d;
	ssl_session_tickets off;
	ssl_session_cache shared:MozSSL:10m;

	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_set_header Host $http_host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Port $server_port;
	proxy_set_header X-Request-Start $msec;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_set_header X-Forwarded-Ssl on;
	proxy_cache_bypass $http_upgrade;

	location /console {
		proxy_pass http://cleanslate_backend:8080;
	}

	location /v1 {
		proxy_pass http://cleanslate_backend:8080;
	}

	location /v2 {
		proxy_pass http://cleanslate_backend:8080;
	}

	location / {
		try_files $uri $uri/index.html;
	}
}
```
