### ISSUE TITLE
Getting 501 response from Hasura server

### ISSUE THREAD

**Issue by ghsysbug** [successible/cleanslate#304]
Hi there,

I really enjoy the idea of cleanslate and its philosophy. I think it would be something I would find very useful and would really like to selfhost, if I can. Unfortunately, I am running into a bit of an error when trying to do so.

I use Nginx Proxy Manager (herein `npm`) as the reverse proxy on a server running Arch Linux. Because of the way I have set it up, I prefer to use Docker's `network` property as opposed to exposing ports. As a result, my `docker-compose.yml` looks like this;

```yml
services:
  database:
    image: postgres:15
    pull_policy: always
    restart: always
    container_name: cspstgres
#    ports:
#      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - proxied
      - cleanslate
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-server:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    pull_policy: always
    restart: always
    container_name: hasura
#    ports:
#      - '${HASURA_PORT:-3680}:8080'
    networks:
      - cleanslate
      - proxied
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_CORS_DOMAIN: https://${NEXT_PUBLIC_HASURA_DOMAIN}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: false
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  authentication-server:
    image: ghcr.io/successible/cleanslate/authentication-server:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    pull_policy: ${PULL_POLICY:-always}
    restart: always
    container_name: csauth
#    ports:
#      - '${AUTHENTICATION_SERVER_PORT:-3601}:3001'
    networks:
      - cleanslate
      - proxied
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      JWT_SIGNING_SECRET: ${JWT_SIGNING_SECRET}
      NEXT_PUBLIC_USE_FIREBASE: ${NEXT_PUBLIC_USE_FIREBASE:-false}
    depends_on:
      - database
      - graphql-server
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  client:
    image: ghcr.io/successible/cleanslate/client:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_CONFIG=${NEXT_PUBLIC_FIREBASE_CONFIG:-{}}
        - NEXT_PUBLIC_LEGAL_LINK=${NEXT_PUBLIC_LEGAL_LINK:-no}
        - NEXT_PUBLIC_LOGIN_WITH_APPLE=${NEXT_PUBLIC_LOGIN_WITH_APPLE:-no}
        - NEXT_PUBLIC_LOGIN_WITH_FACEBOOK=${NEXT_PUBLIC_LOGIN_WITH_FACEBOOK:-no}
        - NEXT_PUBLIC_LOGIN_WITH_GITHUB=${NEXT_PUBLIC_LOGIN_WITH_GITHUB:-no}
        - NEXT_PUBLIC_LOGIN_WITH_GOOGLE=${NEXT_PUBLIC_LOGIN_WITH_GOOGLE:-no}
        - NEXT_PUBLIC_REACT_SENTRY_DSN=${NEXT_PUBLIC_REACT_SENTRY_DSN:-no}
        - NEXT_PUBLIC_USE_FIREBASE=${NEXT_PUBLIC_USE_FIREBASE:-false}
        - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
    pull_policy: ${PULL_POLICY:-always}
    restart: always
    container_name: cleanslate
#    ports:
#      - '${CLIENT_PORT:-3600}:3000'
    networks:
      - cleanslate
      - proxied
    depends_on:
      - database
      - graphql-server
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  database:

networks:
  proxied:
    name: proxied
    external: true
  cleanslate:
    name: cleanslate
```

My `.env` looks like this (website obfuscated);

```
#AUTHENTICATION_SERVER_PORT=3601
#CLIENT_PORT=3600
#HASURA_PORT=3680
#POSTGRES_PORT=5432
HASURA_GRAPHQL_ADMIN_SECRET=password10111213141516______
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256","key":"password12345678______"}'
JWT_SIGNING_SECRET=password10111213141516______
NEXT_PUBLIC_HASURA_DOMAIN=https://website.com
POSTGRES_PASSWORD=password12345678______
```

When I point `npm` to the container `cleanslate` (i.e. the client), I use http as the scheme, the container name (`cleanslate`) and the default port (3000). I then add an SSL certificate via LetsEncrypt to serve the site over https. Given the container is on the same network `proxied` as `npm`, I have been successful in doing this for cleanslate and other services.

I have also created a location, via `npm`, for `cleanslate` relating to the page `console`, also using the http scheme, the container name (`hasura`), and the default port (8080). This loads and presents the login screen, but when I enter the secret, I get the following response from Docker;

`cleanslate  | [::ffff:172.27.0.7]:55118: response:501`

I also get this response (timestamp obfuscated);

`hasura      | {"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"127.0.0.1","method":"GET","status":200,"url":"/healthz"},"operation":{"request_id":"32141772-e223-4b65-ac77-d2b41fdf13c6","request_mode":"non-graphql","response_size":2,"uncompressed_response_size":2},"request_id":"32141772-e223-4b65-ac77-d2b41fdf13c6"},"level":"info","timestamp":"0001-01-01T00:00:00.000+0000","type":"http-log"}`

I am sure I am missing something quite obvious, but I am not quite sure what it is so any help would be much appreciated. Thank you again for making cleanslate.
